
import { Event, EventCategory, Sponsorship, Integration, Exhibitor } from './types';

export const EVENTS_DATA: Event[] = [
  {
    id: '1',
    name: 'SEA Tech Week Singapore',
    description: 'The largest gathering of tech innovators in the region. Focusing on AI, Cloud, and Cybersecurity.',
    category: EventCategory.TECH,
    date: 'Oct 12-14, 2024',
    location: 'Marina Bay Sands, Singapore',
    priceRange: 'S$450 - S$1,200',
    basePrice: 450,
    currency: 'SGD',
    predictedTurnout: 15000,
    historicalTurnout: [12000, 13500, 14200],
    sustainabilityScore: 'A',
    website: '#',
    tags: ['AI', 'Networking', 'Singapore'],
    featured: true,
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: '2',
    name: 'Fintech Jakarta Summit',
    description: 'Connecting banking giants with disruptive fintech startups in Indonesia\'s booming market.',
    category: EventCategory.FINANCE,
    date: 'Nov 05, 2024',
    location: 'JCC Senayan, Jakarta',
    priceRange: 'IDR 2,500,000',
    basePrice: 2500000,
    currency: 'IDR',
    predictedTurnout: 8500,
    historicalTurnout: [6000, 7500, 8100],
    sustainabilityScore: 'B',
    website: '#',
    tags: ['Fintech', 'Banking', 'Indonesia'],
    image: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: '3',
    name: 'Bangkok Creative Expo',
    description: 'A showcase of design, fashion, and digital art from the Mekong region.',
    category: EventCategory.LIFESTYLE,
    date: 'Sep 20-22, 2024',
    location: 'BITEC, Bangkok',
    priceRange: '฿1,500',
    basePrice: 1500,
    currency: 'THB',
    predictedTurnout: 12000,
    historicalTurnout: [10000, 11000, 11500],
    sustainabilityScore: 'A',
    website: '#',
    tags: ['Creative', 'Design', 'Thailand'],
    image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&q=80&w=800'
  }
];

export const SPONSORSHIPS_DATA: Sponsorship[] = [
  {
    id: 's1',
    eventName: 'SEA Tech Week Singapore',
    tier: 'Platinum',
    amount: 'S$50,000',
    description: 'Main stage branding, 20 VIP tickets, and private networking booth.',
  }
];

export const EVENT_CATEGORIES = Object.values(EventCategory);

export const INTEGRATIONS_DATA: Integration[] = [
  { id: 'n8n', name: 'n8n Workflow Engine', category: 'Communication', icon: 'Settings', connected: true, description: 'Master orchestrator for WhatsApp, Email, and Database flows.' },
  { id: '1', name: 'PostgreSQL Cloud', category: 'Database', icon: 'Database', connected: true, description: 'Live attendee logging for audit & PDPA compliance.' },
  { id: '3', name: 'WhatsApp Business', category: 'Support', icon: 'MessageSquare', connected: true, description: 'Automated ticket delivery and check-in updates.' },
  { id: '4', name: 'Salesforce', category: 'CRM', icon: 'Database', connected: true, description: 'Sync lead generation data for exhibitor follow-ups.' },
  { id: '6', name: 'Google Sheets', category: 'Storage', icon: 'HardDrive', connected: false, description: 'Quick export for on-ground staff usage.' },
];

export const EXHIBITORS_DATA: Exhibitor[] = [
  {
    id: 'e1',
    name: 'CloudScale SEA',
    industry: 'Cloud Computing',
    description: 'Enterprise cloud infrastructure for high-growth startups.',
    offerings: ['Cloud Hosting', 'Serverless', 'Database Management'],
    targetAudience: ['CTOs', 'Developers', 'Startups'],
    boothLocation: 'A-12',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=400'
  }
];

export const TRANSLATIONS = {
  en: {
    heroTitle: "Upcoming SEA Events",
    heroSubtitle: "Discover, organize, and sponsor Southeast Asia's leading trade shows and conferences.",
    searchPlaceholder: "Find events (e.g., 'Fintech in Jakarta')...",
    navDirectory: "Directory",
    navSponsorships: "Sponsorships",
    navDashboard: "Dashboard",
    navMatchmaking: "AI Matchmaking",
    login: "Login",
    logout: "Logout",
    createEvent: "Create Event",
    aiSearch: "AI Search",
    find: "Find",
    upcoming: "Upcoming",
    seaEvents: "SEA Events",
    industries: "Industries",
    register: "Register",
    from: "From",
    attendees: "Attendees",
    ecoScore: "Eco Score",
    featured: "Featured",
    allEvents: "All Events",
    tech: "Technology & AI",
    finance: "Fintech & Crypto",
    lifestyle: "Lifestyle & Culture",
    b2b: "B2B Trade Show",
    startup: "Startup & VC",
    overview: "Overview",
    aiAnalytics: "AI Analytics",
    registrations: "Registrations",
    automations: "Automations",
    roiReports: "Post-Event ROI",
    marketing: "AI Marketing",
    integrations: "Integrations",
    totalRegs: "Total Regs",
    checkedIn: "Checked-In",
    revenue: "Revenue",
    staffCheckin: "Staff Check-in",
    walkinScan: "Walk-in Scan",
    myPortal: "My Portal",
    authenticating: "Authenticating...",
    footerPrivacy: "Privacy",
    footerTerms: "Terms",
    footerSubmit: "Submit Event",
    loginTitle: "Login to Nusantara",
    loginSubtitle: "Simulate a login to test role-based access.",
    loginOrganizers: "Organizers",
    loginAttendees: "Attendees",
    loginOrgDesc: "Manage events & sponsorships",
    loginAttDesc: "Buy tickets & AI Matchmaking",
    matchmakingTitle: "AI Smart Matchmaking",
    matchmakingSubtitle: "Our AI analyzes your business goals to curate the perfect list of exhibitors.",
    matchmakingProfile: "Your Match Profile",
    matchmakingFind: "Find My Matches",
    matchmakingJob: "Job Title",
    matchmakingIndustry: "Industry",
    matchmakingGoals: "What are you looking for?",
    matchmakingNoMatches: "No matches generated yet",
    matchmakingReason: "AI Smart Tip",
    integrationsTitle: "Integrations Hub",
    integrationsSubtitle: "Connect your workspace tools to automate event logistics.",
    autoTagline: "Automated Management: Scan any event flyer QR to register instantly",
    regHubTitle: "Nusantara Enrollment Hub",
    fullNameLabel: "Full Badge Name",
    emailLabel: "Digital Correspondence",
    nextSecureAuth: "Next: Secure WhatsApp Auth",
    identitySync: "Identity Sync",
    waGateway: "Regional WhatsApp API Gateway",
    mobileLabel: "Mobile Number (Badge Access)",
    consentLogistics: "Consent to Automated Logistics",
    consentDesc: "Receive QR badges, AI networking match notifications, and official venue alerts via WhatsApp.",
    requestPin: "Request Authorization PIN",
    enterPin: "Enter Authentication PIN",
    verifyPulse: "Verification Pulse",
    syncAccount: "Sync Account",
    accessTier: "Access Tier",
    standardPass: "Standard Pass",
    vipExecutive: "VIP Executive",
    configAiProfile: "Configure AI Profile",
    businessLogic: "Business Logic",
    profRole: "Professional Role",
    netGoal: "Network Goal (For AI Briefing)",
    finalizeSettle: "Finalize Settle",
    settleCheckout: "Settle Checkout",
    prefLocalCurr: "Prefer Local Currency?",
    tierAccess: "Tier Access",
    regNodeFee: "Regional Node Fee",
    totalAuth: "Total Authorized",
    localChannels: "Localized Settlement Channels",
    authSettlement: "Complete Settlement",
    verifySettle: "Verify Settle",
    regAuth: "Registration Authenticated",
    enterPortal: "Enter Portal",
    officialAccount: "Official Account",
    orchestrating: "Orchestrating Experience Flow...",
    syncedVia: "Synced via",
    awaitingPulse: "Awaiting Settle Pulse...",
    paynowDesc: "Direct SGD via SGQR",
    grabpayDesc: "Grab wallet settlement",
    qrisDesc: "GoPay, OVO, Dana, LinkAja",
    vaDesc: "Bank Virtual Account",
    promptpayDesc: "Thai QR Bank Transfer",
    truemoneyDesc: "TrueMoney Wallet"
  },
  id: {
    heroTitle: "Acara SEA Mendatang",
    heroSubtitle: "Temukan, atur, dan sponsori pameran dagang dan konferensi terkemuka di Asia Tenggara.",
    searchPlaceholder: "Cari acara (cth. 'Fintech di Jakarta')...",
    navDirectory: "Direktori",
    navSponsorships: "Sponsor",
    navDashboard: "Dasbor",
    navMatchmaking: "AI Matchmaking",
    login: "Masuk",
    logout: "Keluar",
    createEvent: "Buat Acara",
    aiSearch: "Cari AI",
    find: "Cari",
    upcoming: "Mendatang",
    seaEvents: "Acara SEA",
    industries: "Industri",
    register: "Daftar",
    from: "Mulai",
    attendees: "Peserta",
    ecoScore: "Skor Eko",
    featured: "Unggulan",
    allEvents: "Semua Acara",
    tech: "Teknologi & AI",
    finance: "Fintech & Kripto",
    lifestyle: "Gaya Hidup & Budaya",
    b2b: "Pameran Dagang B2B",
    startup: "Startup & VC",
    overview: "Ikhtisar",
    aiAnalytics: "Analitik AI",
    registrations: "Registrasi",
    automations: "Otomasi",
    roiReports: "ROI Pasca-Acara",
    marketing: "Pemasaran AI",
    integrations: "Integrasi",
    totalRegs: "Total Daftar",
    checkedIn: "Hadir",
    revenue: "Pendapatan",
    staffCheckin: "Check-in Staf",
    walkinScan: "Scan Walk-in",
    myPortal: "Portal Saya",
    authenticating: "Mengautentikasi...",
    footerPrivacy: "Privasi",
    footerTerms: "Ketentuan",
    footerSubmit: "Kirim Acara",
    loginTitle: "Masuk ke Nusantara",
    loginSubtitle: "Simulasikan masuk untuk menguji akses peran.",
    loginOrganizers: "Penyelenggara",
    loginAttendees: "Peserta",
    loginOrgDesc: "Kelola acara & sponsor",
    loginAttDesc: "Beli tiket & AI Matchmaking",
    matchmakingTitle: "Pencocokan Cerdas AI",
    matchmakingSubtitle: "AI kami menganalisis tujuan bisnis Anda untuk menyusun daftar eksibitor yang sempurna.",
    matchmakingProfile: "Profil Cocok Anda",
    matchmakingFind: "Cari Jodoh Bisnis",
    matchmakingJob: "Jabatan",
    matchmakingIndustry: "Industri",
    matchmakingGoals: "Apa yang Anda cari?",
    matchmakingNoMatches: "Belum ada kecocokan",
    matchmakingReason: "Tip Cerdas AI",
    integrationsTitle: "Pusat Integrasi",
    integrationsSubtitle: "Hubungkan alat kerja Anda untuk mengotomatisasi logistik acara.",
    autoTagline: "Manajemen Otomatis: Pindai QR pamflet untuk daftar instan",
    regHubTitle: "Pusat Pendaftaran Nusantara",
    fullNameLabel: "Nama Lengkap (Sesuai ID)",
    emailLabel: "Korespondensi Digital",
    nextSecureAuth: "Berikutnya: Autentikasi WhatsApp",
    identitySync: "Sinkronisasi Identitas",
    waGateway: "Gerbang API WhatsApp Regional",
    mobileLabel: "Nomor Ponsel (Akses Badge)",
    consentLogistics: "Persetujuan Logistik Otomatis",
    consentDesc: "Terima badge QR, notifikasi pencocokan AI, dan peringatan lokasi via WhatsApp.",
    requestPin: "Minta PIN Otorisasi",
    enterPin: "Masukkan PIN Autentikasi",
    verifyPulse: "Denyut Verifikasi",
    syncAccount: "Sinkronkan Akun",
    accessTier: "Tingkat Akses",
    standardPass: "Tiket Standar",
    vipExecutive: "Eksekutif VIP",
    configAiProfile: "Konfigurasi Profil AI",
    businessLogic: "Logika Bisnis",
    profRole: "Peran Profesional",
    netGoal: "Tujuan Jaringan (Untuk Briefing AI)",
    finalizeSettle: "Selesaikan Pembayaran",
    settleCheckout: "Checkout Pembayaran",
    prefLocalCurr: "Gunakan Mata Uang Lokal?",
    tierAccess: "Akses Tingkat",
    regNodeFee: "Biaya Node Regional",
    totalAuth: "Total Diotorisasi",
    localChannels: "Saluran Pembayaran Lokal",
    authSettlement: "Selesaikan Pembayaran",
    verifySettle: "Verifikasi Pembayaran",
    regAuth: "Registrasi Terautentikasi",
    enterPortal: "Masuk ke Portal",
    officialAccount: "Akun Resmi",
    orchestrating: "Mengorkestrasi Alur Pengalaman...",
    syncedVia: "Disinkronkan via",
    awaitingPulse: "Menunggu Sinyal Pembayaran...",
    paynowDesc: "SGD Langsung via SGQR",
    grabpayDesc: "Pembayaran Dompet Grab",
    qrisDesc: "GoPay, OVO, Dana, LinkAja",
    vaDesc: "Akun Virtual Bank",
    promptpayDesc: "Transfer Bank Thai QR",
    truemoneyDesc: "Dompet TrueMoney"
  },
  th: {
    heroTitle: "งานอีเวนต์ SEA ที่กำลังจะมาถึง",
    heroSubtitle: "ค้นพบ จัดระเบียบ และสนับสนุนงานแสดงสินค้าและการประชุมชั้นนำของเอเชียตะวันออกเฉียงใต้",
    searchPlaceholder: "ค้นหางาน (เช่น 'Fintech ในจาการ์ตา')...",
    navDirectory: "ไดเรกทอรี",
    navSponsorships: "การสนับสนุน",
    navDashboard: "แดชบอร์ด",
    navMatchmaking: "AI Matchmaking",
    login: "เข้าสู่ระบบ",
    logout: "ออกจากระบบ",
    createEvent: "สร้างกิจกรรม",
    aiSearch: "ค้นหา AI",
    find: "ค้นหา",
    upcoming: "ที่กำลังจะมาถึง",
    seaEvents: "งาน SEA",
    industries: "อุตสาหกรรม",
    register: "ลงทะเบียน",
    from: "จาก",
    attendees: "ผู้เข้าร่วม",
    ecoScore: "คะแนนอีโก้",
    featured: "แนะนำ",
    allEvents: "กิจกรรมทั้งหมด",
    tech: "เทคโนโลยีและ AI",
    finance: "ฟินเทคและคริปโต",
    lifestyle: "ไลฟ์สไตล์และวัฒนธรรม",
    b2b: "งานแสดงสินค้า B2B",
    startup: "สตาร์ทอัพและ VC",
    overview: "ภาพรวม",
    aiAnalytics: "การวิเคราะห์ AI",
    registrations: "การลงทะเบียน",
    automations: "ระบบอัตโนมัติ",
    roiReports: "ROI หลังงาน",
    marketing: "การตลาด AI",
    integrations: "การเชื่อมต่อ",
    totalRegs: "ยอดลงทะเบียน",
    checkedIn: "เช็คอินแล้ว",
    revenue: "รายได้",
    staffCheckin: "การเช็คอินของเจ้าหน้าที่",
    walkinScan: "สแกนผู้มาติดต่อ",
    myPortal: "พอร์ทัลของฉัน",
    authenticating: "กำลังตรวจสอบสิทธิ์...",
    footerPrivacy: "ความเป็นส่วนตัว",
    footerTerms: "เงื่อนไข",
    footerSubmit: "ส่งกิจกรรม",
    loginTitle: "เข้าสู่ระบบ Nusantara",
    loginSubtitle: "จำลองการเข้าสู่ระบบเพื่อทดสอบการเข้าถึง",
    loginOrganizers: "ผู้จัดงาน",
    loginAttendees: "ผู้เข้าร่วม",
    loginOrgDesc: "จัดการกิจกรรมและสปอนเซอร์",
    loginAttDesc: "ซื้อตั๋วและ AI Matchmaking",
    matchmakingTitle: "การจับคู่ล่วงหน้าด้วย AI",
    matchmakingSubtitle: "AI ของเราวิเคราะห์เป้าหมายธุรกิจของคุณเพื่อค้นหาผู้แสดงสินค้าที่เหมาะสม",
    matchmakingProfile: "โปรไฟล์การจับคู่ของคุณ",
    matchmakingFind: "ค้นหาการจับคู่ของฉัน",
    matchmakingJob: "ตำแหน่งงาน",
    matchmakingIndustry: "อุตสาหกรรม",
    matchmakingGoals: "คุณกำลังมองหาอะไร?",
    matchmakingNoMatches: "ยังไม่มีการจับคู่",
    matchmakingReason: "เคล็ดลับ AI",
    integrationsTitle: "ศูนย์รวมการเชื่อมต่อ",
    integrationsSubtitle: "เชื่อมต่อเครื่องมือเพื่อเพิ่มประสิทธิภาพการจัดการ",
    autoTagline: "การจัดการอัตโนมัติ: สแกน QR บนใบปลิวเพื่อลงทะเบียนทันที",
    regHubTitle: "ศูนย์รับลงทะเบียน Nusantara",
    fullNameLabel: "ชื่อ-นามสกุล (ตามบัตร)",
    emailLabel: "ข้อมูลติดต่อดิจิทัล",
    nextSecureAuth: "ถัดไป: ตรวจสอบสิทธิ์ WhatsApp",
    identitySync: "ซิงค์ข้อมูลประจำตัว",
    waGateway: "เกตเวย์ WhatsApp API ระดับภูมิภาค",
    mobileLabel: "หมายเลขโทรศัพท์ (สำหรับบัตรเข้างาน)",
    consentLogistics: "ยินยอมรับการแจ้งเตือนอัตโนมัติ",
    consentDesc: "รับบัตร QR, การแจ้งเตือนการจับคู่ AI และข่าวสารสถานที่ผ่าน WhatsApp",
    requestPin: "ขอรหัส PIN ยืนยัน",
    enterPin: "กรอกรหัส PIN ตรวจสอบสิทธิ์",
    verifyPulse: "กำลังตรวจสอบสัญญาณ",
    syncAccount: "ซิงค์บัญชี",
    accessTier: "ระดับการเข้าถึง",
    standardPass: "บัตรมาตรฐาน",
    vipExecutive: "บัตรวีไอพีเอ็กเซกคิวทีฟ",
    configAiProfile: "ตั้งค่าโปรไฟล์ AI",
    businessLogic: "ข้อมูลทางธุรกิจ",
    profRole: "ตำแหน่งงาน",
    netGoal: "เป้าหมายการสร้างเครือข่าย",
    finalizeSettle: "สรุปการชำระเงิน",
    settleCheckout: "ชำระเงิน",
    prefLocalCurr: "ต้องการชำระเงินสกุลท้องถิ่น?",
    tierAccess: "การเข้าถึงระดับ",
    regNodeFee: "ค่าธรรมเนียมภูมิภาค",
    totalAuth: "ยอดรวมที่ได้รับอนุญาต",
    localChannels: "ช่องทางการชำระเงินในพื้นที่",
    authSettlement: "ยืนยันการชำระเงิน",
    verifySettle: "ตรวจสอบการชำระเงิน",
    regAuth: "ลงทะเบียนสำเร็จ",
    enterPortal: "เข้าสู่พอร์ทัล",
    officialAccount: "บัญชีทางการ",
    orchestrating: "กำลังจัดเตรียมข้อมูลประสบการณ์...",
    syncedVia: "ซิงค์ข้อมูลผ่าน",
    awaitingPulse: "กำลังรอสัญญาณการชำระเงิน...",
    paynowDesc: "SGD โดยตรงผ่าน SGQR",
    grabpayDesc: "ชำระเงินด้วยกระเป๋าเงิน Grab",
    qrisDesc: "GoPay, OVO, Dana, LinkAja",
    vaDesc: "บัญชีธนาคารเสมือน",
    promptpayDesc: "โอนเงินผ่าน Thai QR",
    truemoneyDesc: "กระเป๋าเงิน TrueMoney"
  },
  zh: {
    heroTitle: "即將到來的東南亞活動",
    heroSubtitle: "發現、組織和贊助東南亞領先的貿易展覽和會議。",
    searchPlaceholder: "搜尋活動（例如“雅加達金融科技”）...",
    navDirectory: "目錄",
    navSponsorships: "贊助",
    navDashboard: "儀表板",
    navMatchmaking: "AI 配對",
    login: "登錄",
    logout: "登出",
    createEvent: "創建活動",
    aiSearch: "AI 搜尋",
    find: "搜尋",
    upcoming: "即將到來",
    seaEvents: "東南亞活動",
    industries: "行業",
    register: "註冊",
    from: "起價",
    attendees: "參加者",
    ecoScore: "環保評分",
    featured: "精選",
    allEvents: "所有活動",
    tech: "技術與 AI",
    finance: "金融科技與加密貨幣",
    lifestyle: "生活方式與文化",
    b2b: "B2B 貿易展",
    startup: "初創與風投",
    overview: "概覽",
    aiAnalytics: "AI 分析",
    registrations: "註冊管理",
    automations: "自動化",
    roiReports: "活動後 ROI",
    marketing: "AI 營銷",
    integrations: "集成",
    totalRegs: "總註冊數",
    checkedIn: "已簽到",
    revenue: "收入",
    staffCheckin: "工作人員簽到",
    walkinScan: "現場掃描",
    myPortal: "我的門戶",
    authenticating: "認證中...",
    footerPrivacy: "隱私政策",
    footerTerms: "使用條款",
    footerSubmit: "提交活動",
    loginTitle: "登錄 Nusantara",
    loginSubtitle: "模擬登錄以測試角色權限。",
    loginOrganizers: "主辦方",
    loginAttendees: "參會者",
    loginOrgDesc: "管理活動與贊助",
    loginAttDesc: "購買門票與 AI 配對",
    matchmakingTitle: "AI 智能配對",
    matchmakingSubtitle: "我們的 AI 分析您的業務目標，為您推薦最合適的參展商。",
    matchmakingProfile: "您的配對檔案",
    matchmakingFind: "開始配對",
    matchmakingJob: "職稱",
    matchmakingIndustry: "行業",
    matchmakingGoals: "您的需求是什麼？",
    matchmakingNoMatches: "尚未生成配對結果",
    matchmakingReason: "AI 智能提示",
    integrationsTitle: "集成中心",
    integrationsSubtitle: "連接您的工作工具以自動化活動後勤。",
    autoTagline: "自動化管理：掃描宣傳單 QR 碼即可立即註冊",
    regHubTitle: "Nusantara 註冊中心",
    fullNameLabel: "證件全名",
    emailLabel: "通訊電子郵件",
    nextSecureAuth: "下一步：WhatsApp 安全認證",
    identitySync: "身份同步",
    waGateway: "東南亞區域 WhatsApp API 網關",
    mobileLabel: "手機號碼（用於入場證）",
    consentLogistics: "同意自動化物流通知",
    consentDesc: "通過 WhatsApp 接收 QR 入場證、AI 配對通知及活動場地提醒。",
    requestPin: "獲取授權 PIN 碼",
    enterPin: "輸入認證 PIN 碼",
    verifyPulse: "驗證脈衝",
    syncAccount: "同步賬戶",
    accessTier: "訪問等級",
    standardPass: "標準通行證",
    vipExecutive: "VIP 行政通行證",
    configAiProfile: "配置 AI 檔案",
    businessLogic: "業務邏輯",
    profRole: "專業職稱",
    netGoal: "網絡目標（用於 AI 簡報）",
    finalizeSettle: "完成結算",
    settleCheckout: "結賬付款",
    prefLocalCurr: "使用本地貨幣支付？",
    tierAccess: "等級訪問",
    regNodeFee: "區域節點費用",
    totalAuth: "授權總額",
    localChannels: "本地結算渠道",
    authSettlement: "完成付款",
    verifySettle: "驗證付款",
    regAuth: "註冊已認證",
    enterPortal: "進入門戶",
    officialAccount: "官方賬號",
    orchestrating: "正在編排活動體驗流...",
    syncedVia: "已同步通過",
    awaitingPulse: "等待結算脈衝...",
    paynowDesc: "通過 SGQR 直接支付 SGD",
    grabpayDesc: "Grab 錢包結算",
    qrisDesc: "GoPay, OVO, Dana, LinkAja",
    vaDesc: "銀行虛擬賬戶",
    promptpayDesc: "泰國 QR 銀行轉賬",
    truemoneyDesc: "TrueMoney 錢包"
  }
};
