
import { Event, EventCategory, Sponsorship, Integration, Exhibitor } from './types';

export const EVENTS_DATA: Event[] = [
  {
    id: '1',
    name: 'SEA Tech Week Singapore',
    description: 'The largest gathering of tech innovators in the region. Focusing on AI, Cloud, and Cybersecurity.',
    category: EventCategory.TECH,
    date: 'Oct 12-14, 2024',
    location: 'Marina Bay Sands, Singapore',
    priceRange: 'S$450 - S$1,200',
    basePrice: 450,
    currency: 'SGD',
    predictedTurnout: 15000,
    historicalTurnout: [12000, 13500, 14200],
    sustainabilityScore: 'A',
    website: '#',
    tags: ['AI', 'Networking', 'Singapore'],
    featured: true,
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: '2',
    name: 'Fintech Jakarta Summit',
    description: 'Connecting banking giants with disruptive fintech startups in Indonesia\'s booming market.',
    category: EventCategory.FINANCE,
    date: 'Nov 05, 2024',
    location: 'JCC Senayan, Jakarta',
    priceRange: 'IDR 2,500,000',
    basePrice: 2500000,
    currency: 'IDR',
    predictedTurnout: 8500,
    historicalTurnout: [6000, 7500, 8100],
    sustainabilityScore: 'B',
    website: '#',
    tags: ['Fintech', 'Banking', 'Indonesia'],
    image: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: '3',
    name: 'Bangkok Creative Expo',
    description: 'A showcase of design, fashion, and digital art from the Mekong region.',
    category: EventCategory.LIFESTYLE,
    date: 'Sep 20-22, 2024',
    location: 'BITEC, Bangkok',
    priceRange: '฿1,500',
    basePrice: 1500,
    currency: 'THB',
    predictedTurnout: 12000,
    historicalTurnout: [10000, 11000, 11500],
    sustainabilityScore: 'A',
    website: '#',
    tags: ['Creative', 'Design', 'Thailand'],
    image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&q=80&w=800'
  }
];

export const SPONSORSHIPS_DATA: Sponsorship[] = [
  {
    id: 's1',
    eventName: 'SEA Tech Week Singapore',
    tier: 'Platinum',
    amount: 'S$50,000',
    description: 'Main stage branding, 20 VIP tickets, and private networking booth.',
  }
];

export const EVENT_CATEGORIES = Object.values(EventCategory);

export const INTEGRATIONS_DATA: Integration[] = [
  { id: 'n8n', name: 'n8n Workflow Engine', category: 'Communication', icon: 'Settings', connected: true, description: 'Master orchestrator for WhatsApp, Email, and Database flows.' },
  { id: '1', name: 'PostgreSQL Cloud', category: 'Database', icon: 'Database', connected: true, description: 'Live attendee logging for audit & PDPA compliance.' },
  { id: '3', name: 'WhatsApp Business', category: 'Support', icon: 'MessageSquare', connected: true, description: 'Automated ticket delivery and check-in updates.' },
  { id: '4', name: 'Salesforce', category: 'CRM', icon: 'Database', connected: true, description: 'Sync lead generation data for exhibitor follow-ups.' },
  { id: '6', name: 'Google Sheets', category: 'Storage', icon: 'HardDrive', connected: false, description: 'Quick export for on-ground staff usage.' },
];

export const EXHIBITORS_DATA: Exhibitor[] = [
  {
    id: 'e1',
    name: 'CloudScale SEA',
    industry: 'Cloud Computing',
    description: 'Enterprise cloud infrastructure for high-growth startups.',
    offerings: ['Cloud Hosting', 'Serverless', 'Database Management'],
    targetAudience: ['CTOs', 'Developers', 'Startups'],
    boothLocation: 'A-12',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=400'
  }
];

const EN_TRANS = {
  heroTitle: "Upcoming SEA Events",
  heroSubtitle: "Discover, organize, and sponsor Southeast Asia's leading trade shows and conferences.",
  searchPlaceholder: "Find events (e.g., 'Fintech in Jakarta')...",
  navDirectory: "Directory",
  navSponsorships: "Sponsorships",
  navDashboard: "Dashboard",
  navMatchmaking: "AI Matchmaking",
  login: "Login",
  logout: "Logout",
  createEvent: "Create Event",
  aiSearch: "AI Search",
  find: "Find",
  upcoming: "Upcoming",
  seaEvents: "SEA Events",
  industries: "Industries",
  register: "Register",
  from: "From",
  attendees: "Attendees",
  ecoScore: "Eco Score",
  featured: "Featured",
  allEvents: "All Events",
  tech: "Technology & AI",
  finance: "Fintech & Crypto",
  lifestyle: "Lifestyle & Culture",
  b2b: "B2B Trade Show",
  startup: "Startup & VC",
  overview: "Overview",
  aiAnalytics: "AI Analytics",
  registrations: "Registrations",
  automations: "Automations",
  roiReports: "Post-Event ROI",
  marketing: "AI Marketing",
  integrations: "Integrations",
  totalRegs: "Total Regs",
  checkedIn: "Checked-In",
  revenue: "Revenue",
  staffCheckin: "Staff Check-in",
  walkinScan: "Walk-in Scan",
  myPortal: "My Portal",
  authenticating: "Authenticating...",
  footerPrivacy: "Privacy",
  footerTerms: "Terms",
  footerSubmit: "Submit Event",
  loginTitle: "Login to Nusantara",
  loginSubtitle: "Simulate a login to test role-based access.",
  loginOrganizers: "Organizers",
  loginAttendees: "Attendees",
  loginOrgDesc: "Manage events & sponsorships",
  loginAttDesc: "Buy tickets & AI Matchmaking",
  matchmakingTitle: "AI Smart Matchmaking",
  matchmakingSubtitle: "Our AI analyzes your business goals to curate the perfect list of exhibitors.",
  matchmakingProfile: "Your Match Profile",
  matchmakingFind: "Find My Matches",
  matchmakingJob: "Job Title",
  matchmakingIndustry: "Industry",
  matchmakingGoals: "What are you looking for?",
  matchmakingNoMatches: "No matches generated yet",
  matchmakingReason: "AI Smart Tip",
  integrationsTitle: "Integrations Hub",
  integrationsSubtitle: "Connect your workspace tools to automate event logistics.",
  autoTagline: "Automated Management: Scan any event flyer QR to register instantly",
  regHubTitle: "Nusantara Enrollment Hub",
  fullNameLabel: "Full Badge Name",
  emailLabel: "Digital Correspondence",
  nextSecureAuth: "Next: Secure WhatsApp Auth",
  identitySync: "Identity Sync",
  waGateway: "Regional WhatsApp API Gateway",
  mobileLabel: "Mobile Number (Badge Access)",
  consentLogistics: "Consent to Automated Logistics",
  consentDesc: "Receive QR badges, AI networking match notifications, and official venue alerts via WhatsApp.",
  requestPin: "Request Authorization PIN",
  enterPin: "Enter Authentication PIN",
  verifyPulse: "Verification Pulse",
  syncAccount: "Sync Account",
  accessTier: "Access Tier",
  standardPass: "Standard Pass",
  vipExecutive: "VIP Executive",
  configAiProfile: "Configure AI Profile",
  businessLogic: "Business Logic",
  profRole: "Professional Role",
  netGoal: "Network Goal (For AI Briefing)",
  finalizeSettle: "Finalize Settle",
  settleCheckout: "Settle Checkout",
  prefLocalCurr: "Prefer Local Currency?",
  tierAccess: "Tier Access",
  regNodeFee: "Regional Node Fee",
  totalAuth: "Total Authorized",
  localChannels: "Localized Settlement Channels",
  authSettlement: "Complete Settlement",
  verifySettle: "Verify Settle",
  regAuth: "Registration Authenticated",
  enterPortal: "Enter Portal",
  officialAccount: "Official Account",
  orchestrating: "Orchestrating Experience Flow...",
  syncedVia: "Synced via",
  awaitingPulse: "Awaiting Settle Pulse...",
  paynowDesc: "Direct SGD via SGQR",
  grabpayDesc: "Grab wallet settlement",
  qrisDesc: "GoPay, OVO, Dana, LinkAja",
  vaDesc: "Bank Virtual Account",
  promptpayDesc: "Thai QR Bank Transfer",
  truemoneyDesc: "TrueMoney Wallet",
  navIdentity: "Identity",
  navAuth: "Auth",
  navTier: "Tier",
  navReview: "Review",
  navSettle: "Settle",
  autoMgmtCore: "Automated Management Core",
  autoRegTerminal: "Automated Registration & Attendee Terminal",
  autoRegDesc: "Deploy instant check-in nodes across your venue. Our AI-driven handshake protocol ensures zero-friction arrival and instant WhatsApp badge delivery.",
  opticalHandshake: "Optical Handshake",
  startQuickCheckin: "Start Quick Check-in",
  pulseLogs: "Real-time Pulse Logs",
  listeningSignals: "Listening for Node signals...",
  autoSettings: "Automation Settings",
  autoHandshake: "Auto-Handshake",
  instantWA: "Instant WhatsApp",
  aiSmoothing: "Pro Feature: AI Queue Smoothing",
  termVelocity: "Terminal Velocity",
  avgHandshake: "Avg Handshake Speed",
  optNodeActive: "Optimization Node Active"
};

export const TRANSLATIONS: Record<string, any> = {
  en: EN_TRANS,
  id: {
    ...EN_TRANS,
    heroTitle: "Acara SEA Mendatang",
    heroSubtitle: "Temukan, atur, dan sponsori pameran dagang dan konferensi terkemuka di Asia Tenggara.",
    searchPlaceholder: "Cari acara (cth. 'Fintech di Jakarta')...",
    navDirectory: "Direktori",
    navSponsorships: "Sponsor",
    navDashboard: "Dasbor",
    navMatchmaking: "AI Matchmaking",
    login: "Masuk",
    logout: "Keluar",
    createEvent: "Buat Acara",
    aiSearch: "Cari AI",
    find: "Cari",
    register: "Daftar",
    attendees: "Peserta",
    overview: "Ikhtisar",
    aiAnalytics: "Analitik AI",
    registrations: "Registrasi",
    automations: "Otomasi",
    integrations: "Integrasi",
    regHubTitle: "Pusat Pendaftaran Nusantara",
    fullNameLabel: "Nama Lengkap (Sesuai ID)",
    emailLabel: "Korespondensi Digital",
    nextSecureAuth: "Berikutnya: Autentikasi WhatsApp",
    identitySync: "Sinkronisasi Identitas",
    waGateway: "Gerbang API WhatsApp Regional",
    mobileLabel: "Nomor Ponsel (Akses Badge)",
    consentLogistics: "Persetujuan Logistik Otomatis",
    consentDesc: "Terima badge QR, notifikasi pencocokan AI, dan peringatan lokasi via WhatsApp.",
    requestPin: "Minta PIN Otorisasi",
    syncAccount: "Sinkronkan Akun",
    accessTier: "Tingkat Akses",
    finalizeSettle: "Selesaikan Pembayaran",
    settleCheckout: "Checkout Pembayaran",
    autoRegTerminal: "Terminal Registrasi & Peserta Otomatis",
  },
  th: {
    ...EN_TRANS,
    heroTitle: "งานอีเวนต์ SEA ที่กำลังจะมาถึง",
    heroSubtitle: "ค้นพบ จัดระเบียบ และสนับสนุนงานแสดงสินค้าและการประชุมชั้นนำของเอเชียตะวันออกเฉียงใต้",
    searchPlaceholder: "ค้นหางาน (เช่น 'Fintech ในจาการ์ตา')...",
    navDirectory: "ไดเรกทอรี",
    navSponsorships: "การสนับสนุน",
    navDashboard: "แดชบอร์ด",
    navMatchmaking: "AI Matchmaking",
    login: "เข้าสู่ระบบ",
    logout: "ออกจากระบบ",
    aiSearch: "ค้นหา AI",
    find: "ค้นหา",
    register: "ลงทะเบียน",
    attendees: "ผู้เข้าร่วม",
    overview: "ภาพรวม",
    aiAnalytics: "การวิเคราะห์ AI",
    registrations: "การลงทะเบียน",
    automations: "ระบบอัตโนมัติ",
    regHubTitle: "ศูนย์รับลงทะเบียน Nusantara",
    fullNameLabel: "ชื่อ-นามสกุล (ตามบัตร)",
    emailLabel: "ข้อมูลติดต่อดิจิทัล",
    nextSecureAuth: "ถัดไป: ตรวจสอบสิทธิ์ WhatsApp",
    identitySync: "ซิงค์ข้อมูลประจำตัว",
    waGateway: "เกตเวย์ WhatsApp API ระดับภูมิภาค",
    mobileLabel: "หมายเลขโทรศัพท์ (สำหรับบัตรเข้างาน)",
    consentLogistics: "ยินยอมรับการแจ้งเตือนอัตโนมัติ",
    requestPin: "ขอรหัส PIN ยืนยัน",
    syncAccount: "ซิงค์บัญชี",
    finalizeSettle: "สรุปการชำระเงิน",
    settleCheckout: "ชำระเงิน",
    autoRegTerminal: "เทอร์มินัลการลงทะเบียนและผู้เข้าร่วมอัตโนมัติ",
  },
  zh: {
    ...EN_TRANS,
    heroTitle: "即將到來的東南亞活動",
    heroSubtitle: "發現、組織和贊助東南亞領先的貿易展覽和會議。",
    searchPlaceholder: "搜尋活動（例如“雅加達金融科技”）...",
    navDirectory: "目錄",
    navSponsorships: "贊助",
    navDashboard: "儀表板",
    navMatchmaking: "AI 配對",
    login: "登錄",
    logout: "登出",
    aiSearch: "AI 搜尋",
    find: "搜尋",
    register: "註冊",
    attendees: "參加者",
    overview: "概覽",
    aiAnalytics: "AI 分析",
    registrations: "註冊管理",
    automations: "自動化",
    regHubTitle: "Nusantara 註冊中心",
    fullNameLabel: "證件全名",
    emailLabel: "通訊電子郵件",
    nextSecureAuth: "下一步：WhatsApp 安全認證",
    identitySync: "身份同步",
    waGateway: "東南亞區域 WhatsApp API 網關",
    mobileLabel: "手機號碼（用於入場證）",
    consentLogistics: "同意自動化物流通知",
    requestPin: "獲取授權 PIN 碼",
    syncAccount: "同步賬戶",
    finalizeSettle: "完成結算",
    settleCheckout: "結賬付款",
    autoRegTerminal: "自動註冊與參會者終端",
  },
  vi: {
    ...EN_TRANS,
    heroTitle: "Sự kiện SEA sắp tới",
    navDirectory: "Danh mục",
    navSponsorships: "Tài trợ",
    navDashboard: "Bảng điều khiển",
    register: "Đăng ký",
    attendees: "Người tham dự",
    overview: "Tổng quan",
    registrations: "Đăng ký",
    automations: "Tự động hóa",
    regHubTitle: "Trung tâm Đăng ký Nusantara",
    fullNameLabel: "Họ tên đầy đủ (trên thẻ)",
    emailLabel: "Thư từ kỹ thuật số",
    nextSecureAuth: "Tiếp theo: Xác thực WhatsApp Bảo mật",
    identitySync: "Đồng bộ danh tính",
    mobileLabel: "Số điện thoại (Truy cập thẻ)",
    consentLogistics: "Đồng ý nhận thông báo hậu cần",
    requestPin: "Yêu cầu mã PIN ủy quyền",
    syncAccount: "Đồng bộ tài khoản",
    finalizeSettle: "Hoàn tất thanh toán",
    settleCheckout: "Thanh toán",
    autoRegTerminal: "Thiết bị Đăng ký & Người tham dự Tự động",
  },
  ms: {
    ...EN_TRANS,
    heroTitle: "Acara SEA Akan Datang",
    navDirectory: "Direktori",
    navSponsorships: "Penajaan",
    navDashboard: "Papan Pemuka",
    register: "Daftar",
    attendees: "Peserta",
    overview: "Gambaran Keseluruhan",
    registrations: "Pendaftaran",
    automations: "Automatik",
    regHubTitle: "Pusat Pendaftaran Nusantara",
    fullNameLabel: "Nama Penuh (Untuk Pas)",
    emailLabel: "Korespondensi Digital",
    nextSecureAuth: "Seterusnya: Pengesahan WhatsApp Selamat",
    identitySync: "Sinkronisasi Identiti",
    mobileLabel: "Nombor Mudah Alih (Akses Pas)",
    consentLogistics: "Persetujuan Logistik Automatik",
    requestPin: "Minta PIN Kebenaran",
    syncAccount: "Sinkronkan Akaun",
    finalizeSettle: "Selesaikan Pembayaran",
    settleCheckout: "Checkout Pembayaran",
    autoRegTerminal: "Terminal Pendaftaran & Peserta Automatik",
  },
  tl: {
    ...EN_TRANS,
    heroTitle: "Mga Darating na Kaganapan sa SEA",
    navDirectory: "Direktoryo",
    navSponsorships: "Sponsorship",
    navDashboard: "Dashboard",
    register: "Magrehistro",
    attendees: "Mga Dadalo",
    overview: "Pangkalahatang-ideya",
    registrations: "Mga Rehistrasyon",
    automations: "Automations",
    regHubTitle: "Nusantara Enrollment Hub",
    fullNameLabel: "Buong Pangalan sa Badge",
    emailLabel: "Digital na Pakikipag-ugnayan",
    nextSecureAuth: "Susunod: Secure na WhatsApp Auth",
    identitySync: "Identity Sync",
    mobileLabel: "Numero ng Mobile (Badge Access)",
    consentLogistics: "Pahintulot sa Automated Logistics",
    requestPin: "Humingi ng Authorization PIN",
    syncAccount: "I-sync ang Account",
    finalizeSettle: "I-finalize ang Pagbabayad",
    settleCheckout: "Settle Checkout",
    autoRegTerminal: "Automated Registration at Attendee Terminal",
  },
  km: {
    ...EN_TRANS,
    heroTitle: "ព្រឹត្តិការណ៍ SEA នាពេលខាងមុខ",
    navDirectory: "បញ្ជីឈ្មោះ",
    navSponsorships: "ការឧបត្ថម្ភ",
    navDashboard: "ផ្ទាំងគ្រប់គ្រង",
    register: "ចុះឈ្មោះ",
    attendees: "អ្នកចូលរួម",
    overview: "ទិដ្ឋភាពទូទៅ",
    registrations: "ការចុះឈ្មោះ",
    automations: "ស្វ័យប្រវត្តិកម្ម",
    regHubTitle: "មជ្ឈមណ្ឌលចុះឈ្មោះ Nusantara",
    fullNameLabel: "ឈ្មោះពេញលើប័ណ្ណ",
    emailLabel: "ការឆ្លើយឆ្លងឌីជីថល",
    nextSecureAuth: "បន្ទាប់៖ ការផ្ទៀងផ្ទាត់ WhatsApp",
    identitySync: "ការធ្វើសមកាលកម្មអត្តសញ្ញាណ",
    mobileLabel: "លេខទូរស័ព្ទ (សម្រាប់ការចូលប្រើប័ណ្ណ)",
    consentLogistics: "ការយល់ព្រមចំពោះភស្តុភារស្វ័យប្រវត្តិ",
    requestPin: "ស្នើសុំលេខកូដ PIN",
    syncAccount: "ធ្វើសមកាលកម្មគណនី",
    finalizeSettle: "បញ្ចប់ការទូទាត់",
    settleCheckout: "ការទូទាត់ប្រាក់",
    autoRegTerminal: "ស្ថានីយចុះឈ្មោះស្វ័យប្រវត្តិ និងអ្នកចូលរួម",
  },
  my: {
    ...EN_TRANS,
    heroTitle: "လာမည့် SEA ပွဲများ",
    navDirectory: "လမ်းညွှန်",
    navSponsorships: "စပွန်ဆာပေးမှုများ",
    navDashboard: "ဒက်ရှ်ဘုတ်",
    register: "စာရင်းသွင်းရန်",
    attendees: "တက်ရောက်သူများ",
    overview: "ခြုံငုံသုံးသပ်ချက်",
    registrations: "စာရင်းပေးသွင်းမှုများ",
    automations: "အလိုအလျောက်စနစ်များ",
    regHubTitle: "Nusantara စာရင်းသွင်းမှုဗဟို",
    fullNameLabel: "ဘတ်ဂျ်ပေါ်ရှိ အမည်အပြည့်အစုံ",
    emailLabel: "ဒီဂျစ်တယ် ဆက်သွယ်မှု",
    nextSecureAuth: "နောက်တစ်ခု- WhatsApp အတည်ပြုချက်",
    identitySync: "အထောက်အထား ထပ်တူပြုခြင်း",
    mobileLabel: "မိုဘိုင်းလ်ဖုန်းနံပါတ်",
    consentLogistics: "အလိုအလျောက် ထောက်ပံ့ပို့ဆောင်ရေး သဘောတူညီချက်",
    requestPin: "PIN ကုဒ် တောင်းဆိုရန်",
    syncAccount: "အကောင့် ထပ်တူပြုရန်",
    finalizeSettle: "ငွေပေးချေမှုကို အတည်ပြုရန်",
    settleCheckout: "ငွေပေးချေမှု ပြီးမြောက်ရန်",
    autoRegTerminal: "အလိုအလျောက် စာရင်းသွင်းခြင်းနှင့် တက်ရောက်သူ ဂိတ်",
  },
  lo: {
    ...EN_TRANS,
    heroTitle: "ກິດຈະກຳ SEA ທີ່ຈະມາເຖິງ",
    navDirectory: "ລາຍຊື່",
    navSponsorships: "ການອຸປະຖຳ",
    navDashboard: "ແຜງຄວບຄຸມ",
    register: "ລົງທະບຽນ",
    attendees: "ຜູ້ເຂົ້າຮ່ວມ",
    overview: "ພາບລວມ",
    registrations: "ການລົງທະບຽນ",
    automations: "ລະບົບອັດຕະໂນມັດ",
    regHubTitle: "ສູນລົງທະບຽນ Nusantara",
    fullNameLabel: "ຊື່ເຕັມໃນບັດ",
    emailLabel: "ການຕິດຕໍ່ດິຈິຕອນ",
    nextSecureAuth: "ຕໍ່ໄປ: ການຢືນຢັນ WhatsApp",
    identitySync: "ການເຊື່ອມໂຍງຕົວຕົນ",
    mobileLabel: "ເບີໂທລະສັບ (ສຳລັບເຂົ້າງານ)",
    consentLogistics: "ການຍອມຮັບການຈັດການອັດຕະໂນມັດ",
    requestPin: "ຂໍລະຫັດ PIN",
    syncAccount: "ເຊື່ອມໂຍງບັນຊີ",
    finalizeSettle: "ສະຫຼຸບການຊຳລະເງິນ",
    settleCheckout: "ຊຳລະເງິນ",
    autoRegTerminal: "ສະຖານີລົງທະບຽນອັດຕະໂນມັດ ແລະ ຜູ້ເຂົ້າຮ່ວມ",
  }
};

// Ensure all new keys fallback to English if not defined for each language
const ALL_KEYS = Object.keys(TRANSLATIONS.en);
Object.keys(TRANSLATIONS).forEach(lang => {
  if (lang === 'en') return;
  ALL_KEYS.forEach(key => {
    if (!TRANSLATIONS[lang][key]) {
      TRANSLATIONS[lang][key] = TRANSLATIONS.en[key];
    }
  });
});
